sudo: required
jdk:
- openjdk8
services:
- docker
branches:
  only:
  - master  
install:
- sudo apt-get -qq update
- sudo apt-get -qq -y install graphviz realpath
script:
- curl -fsSL https://get.nextflow.io | bash
- ./nextflow run .
- ./nextflow run . -with-docker 